[project]
name = "shot-vs-pass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sebastian Smith", email = "sebastianlukesmith@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "mplsoccer>=1.8.0",
    "pandas>=3.0.5",
    "statsbombpy>=1.22.0",
]

[project.scripts]
shot-vs-pass = "shot_vs_pass:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
